### ISSUE TITLE
PSPP can not retrieve data from hot-standby PostgreSQL 9.5 database.

### ISSUE THREAD

**Issue by CC-Hsu** [lemenkov/pspp#1]
Hi,

I tried to access data following the documentation [9.4.2 Postgres Database Queries](https://www.gnu.org/software/pspp/manual/html_node/GET-DATA-_002fTYPE_003dPSQL.html) section but got the following error.

```
PSPP> GET DATA /TYPE=PSQL
    > /CONNECT="host=127.0.0.1 port=5433 user=cchsu dbname=postgres"       
    > /SQL="SELECT * FROM tst"
    > /UNENCRYPTED.

error: Error from psql source: ERROR:  cannot use serializable mode in a hot
standby
HINT:  You can use REPEATABLE READ instead.
```

I pinned down to `/src/data/psql-reader.c` and found

```
ds_init_cstr (&query,
        "BEGIN READ ONLY ISOLATION LEVEL SERIALIZABLE; "
"DECLARE  pspp BINARY CURSOR FOR ");
```

It seems that PSPP can not query from a hot-standby database because the isolation level is set to `SERIALIZABLE` in this line.

Is it possible to improve this?

Maybe set the isolation level to `REPEATABLE READ` instead of `SERIALIZABLE`( ['PostgreSQL: Documentation: 9.5: SET TRANSACTION'](https://www.postgresql.org/docs/9.5/static/sql-set-transaction.html) )?

Thank you.

**Comment by lemenkov** [comment]
I'm terribly sorry for the confusion, but I'm not maintaining this. Could you please send this to the original PSPP upstream?

https://savannah.gnu.org/bugs/?func=additem&group=pspp

**Comment by CC-Hsu** [comment]
Hi,

Thanks to your reply.

I found the mailing list and issued the problem.

And the problem is solved now.

Sorry for mistakenly asking the question to you.

Beat regards.

2016年8月24日 下午7:55於 "Peter Lemenkov" <notifications@github.com>寫道：
